name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate-hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration